{"@t":"2020-06-28T11:43:16.7899362Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:53:41.0198971Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:12.7836442Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:28.8786504Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:31.0174533Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T11:54:31.0799453Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:39.0016419Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:41.0261472Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:42.7246362Z","@mt":"Email sent. From: ryan_7229@hotmail.co.uk, To: string, Subject: Football Banter - Please confirm your registration, Content: This should be link to confirmation page. For now, please execute HTTP request PATCH http://localhost:5000/userAccess/userRegistrations/7df5b1da-9016-4382-8a08-08d81b5a5302/confirm.","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:45.2671486Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:00.1594032Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:15.2012602Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:30.2660501Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:45.1906318Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:00.2455892Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:15.1241590Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:30.2478015Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:45.1937835Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:00.1290367Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:15.1777445Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:30.2574651Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:45.1297192Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:00.1240318Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:15.2309332Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:30.1302756Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:45.1260739Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:00.1411892Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:15.1292415Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:30.2221775Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:45.1331193Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:00.1286189Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:15.2521718Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:49.6699468Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:50.5813342Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:04.8531281Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:15.2061502Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:30.2958616Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:45.1201401Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:00.2061652Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:15.1301946Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:30.1203613Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:45.2667757Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:00.2076763Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:15.1177727Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:30.1338617Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:45.2771398Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:06:00.1238067Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:06:15.2271997Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:23:47.3782546Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:23:50.4419624Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:23:50.5651202Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T12:24:01.2396103Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:24:15.5875948Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:860161f3-1465-4a50-8848-43a7e2fdddfd\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:24:30.1775118Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:24:45.1412008Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:25:00.2015705Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:25:15.3162190Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:25:30.2271649Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:25:45.1274491Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:26:00.2181730Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:26:15.2339518Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:26:30.2244608Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:26:45.1282838Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:27:00.1238460Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:7b149102-f47b-4fe6-b4d4-5b71ad070288\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:27:15.2459086Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:860161f3-1465-4a50-8848-43a7e2fdddfd\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:27:30.2685689Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:27:45.2668139Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:860161f3-1465-4a50-8848-43a7e2fdddfd\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:28:00.2923256Z","@mt":"Job DEFAULT.5e568de5-df39-4a38-ba1d-46db7b00f229 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:5893cbb0-ebb8-411b-b1bf-4d019a1621e3\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:29:23.2956036Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:29:25.8620256Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:29:25.9347600Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T12:29:31.3908055Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:de9e20cb-e86d-4906-989c-c89937fa0b21\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:29:45.1421853Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:af4738c8-535b-49fc-b421-6cb0d4037457\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:30:00.2395501Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:af4738c8-535b-49fc-b421-6cb0d4037457\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:30:15.1558124Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:30:30.1151022Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:30:45.1803977Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:de9e20cb-e86d-4906-989c-c89937fa0b21\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:31:00.2352216Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:de9e20cb-e86d-4906-989c-c89937fa0b21\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:31:15.1776805Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:31:30.2631508Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:31:45.2312509Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:32:00.1813369Z","@mt":"Job DEFAULT.26f3fa4d-0956-4962-ad18-3c079ff70a0a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:6f937200-b01f-48fd-ad8f-13124000fb8a\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:32:31.9517370Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:32:34.7244192Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:32:34.8158118Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T12:32:46.3347325Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:e3a724fb-9b4e-4fac-ab01-eb74b13c2caa\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:33:00.2286864Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:9105de13-02ac-4aa9-8657-b2f18c90a092\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:33:15.1445296Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:9105de13-02ac-4aa9-8657-b2f18c90a092\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:33:30.2138190Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:e3a724fb-9b4e-4fac-ab01-eb74b13c2caa\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:33:45.1456138Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:9105de13-02ac-4aa9-8657-b2f18c90a092\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:34:00.1272071Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:f3643fe4-9a42-4625-8012-8f4b15786530\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:34:15.1384286Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:f3643fe4-9a42-4625-8012-8f4b15786530\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:34:30.2904116Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:9105de13-02ac-4aa9-8657-b2f18c90a092\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:34:45.3023210Z","@mt":"Job DEFAULT.3c3a6ab1-1d9f-4ade-a5f3-b8373d3bec35 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:f3643fe4-9a42-4625-8012-8f4b15786530\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:35:35.8398028Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:35:38.3191543Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:35:38.4034243Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T12:36:00.8539046Z","@mt":"Job DEFAULT.4565b8e8-b323-4657-9983-8ccf2f49c3cc threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:46d55b0b-e160-4957-b643-2f7549b19cd6\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:36:58.6902713Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:37:01.5087193Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:37:01.6021976Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T12:37:37.2063062Z","@mt":"Job DEFAULT.37657bc9-edc5-4af5-8805-bde25551d061 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\nInvalid column name 'Data'.\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:1df99a9b-2a5f-4c32-9cd4-cff1a406129f\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:41:06.3768969Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:41:51.8953587Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:42:20.1099201Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:43:13.9202431Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:50:00.4226532Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:50:35.9041754Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:51:48.8281062Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:52:20.0668823Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:55:15.5345487Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:56:25.7680911Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T12:56:28.8036342Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T12:56:28.8780447Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T15:15:17.3398101Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:01:57.8695943Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:02:14.2211152Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:05:42.5100037Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:05:44.6196724Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T16:05:44.6724090Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.0919411Z","@mt":"Job DEFAULT.51d6c6e0-e113-42a3-8648-74743a5bba76 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 40\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:cb12b565-cdbc-4e6e-91bd-c7cdf71ff304\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.1987884Z","@mt":"Job DEFAULT.2f8b5e0a-95a4-4747-8d89-7e50169b6252 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:57686ae8-288d-403e-9d58-0f011873a0d3\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.4859498Z","@mt":"Job DEFAULT.2f8b5e0a-95a4-4747-8d89-7e50169b6252 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:57686ae8-288d-403e-9d58-0f011873a0d3\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.5468027Z","@mt":"Job DEFAULT.51d6c6e0-e113-42a3-8648-74743a5bba76 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 40\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:cb12b565-cdbc-4e6e-91bd-c7cdf71ff304\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.6406361Z","@mt":"Job DEFAULT.7d4c42be-c892-4477-9ef7-3376d7cd6f8c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:60ba16ed-3b8e-4dfc-8aa4-65cf1ac25e03\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:01.9722531Z","@mt":"Job DEFAULT.7d4c42be-c892-4477-9ef7-3376d7cd6f8c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Users.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:60ba16ed-3b8e-4dfc-8aa4-65cf1ac25e03\r\nError Number:208,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:55.7127398Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:06:57.2936373Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T16:06:57.3555332Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T16:53:17.1168660Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:53:19.7120191Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T16:53:19.7730487Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:13:14.6127229Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:13:16.6886386Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:13:16.7441207Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:13:50.9005891Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:13:52.4218983Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:13:52.4982402Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:26:54.4136318Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:26:57.1239805Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:26:57.2455893Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:37:25.5716953Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:37:28.9369177Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:37:29.0933427Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:47:29.7151397Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:47:32.6032904Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:47:32.7367025Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T17:49:59.5334767Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:50:02.6927188Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T17:50:02.8913166Z","@mt":"Quartz started.","Module":"UserAccess"}
