{"@t":"2020-06-28T11:43:16.7899362Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:53:41.0198971Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:12.7836442Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:28.8786504Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T11:54:31.0174533Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-06-28T11:54:31.0799453Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:39.0016419Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:41.0261472Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:42.7246362Z","@mt":"Email sent. From: ryan_7229@hotmail.co.uk, To: string, Subject: Football Banter - Please confirm your registration, Content: This should be link to confirmation page. For now, please execute HTTP request PATCH http://localhost:5000/userAccess/userRegistrations/7df5b1da-9016-4382-8a08-08d81b5a5302/confirm.","Module":"UserAccess"}
{"@t":"2020-06-28T11:56:45.2671486Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:00.1594032Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:15.2012602Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:30.2660501Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:57:45.1906318Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:00.2455892Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:15.1241590Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:30.2478015Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:58:45.1937835Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:00.1290367Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:15.1777445Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:30.2574651Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T11:59:45.1297192Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:89fdc637-e23a-4f14-bbf4-51a928e84b34\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:00.1240318Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:15.2309332Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:30.1302756Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:00:45.1260739Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:00.1411892Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:15.1292415Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:30.2221775Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:01:45.1331193Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:00.1286189Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:15.2521718Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:49.6699468Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:02:50.5813342Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:04.8531281Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:15.2061502Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:30.2958616Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:03:45.1201401Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:00.2061652Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:15.1301946Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:80cd8018-9318-4fc7-a140-c996fdb4e6f4\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:30.1203613Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:04:45.2667757Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:00.2076763Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:15.1177727Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:30.1338617Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:05:45.2771398Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c4509454-f1a6-4646-b8e8-b5dfcd4bef39\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:06:00.1238067Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
{"@t":"2020-06-28T12:06:15.2271997Z","@mt":"Job DEFAULT.a513f3ad-f7cd-48b6-8b44-d64d874abacd threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ProcessedDate'.\r\nInvalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\r\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:4c6bb6d6-3259-439c-bb29-047a848065a0\r\nError Number:207,State:1,Class:16","Module":"UserAccess"}
