{"@t":"2020-06-28T15:06:24.1120063Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:09:04.1737432Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:09:05.1949624Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:09:05.2464945Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T15:13:18.7053851Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:16:59.8119882Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:17:15.4013560Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:17:16.6043252Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:17:16.6757025Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T15:17:30.6451517Z","@mt":"Job DEFAULT.01c21490-915c-4ba5-a2f9-084fa72b55c1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'User.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2df53c4b-8af0-4056-8ee8-25cafd780daa\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:17:30.8858641Z","@mt":"Job DEFAULT.9095148d-266a-470d-b526-98b8b9daa606 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2df53c4b-8af0-4056-8ee8-25cafd780daa\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:17:31.0018244Z","@mt":"Job DEFAULT.2fc32914-deb8-4fd9-b1a8-faf394421eb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:340d5f11-6f16-4dbd-8dce-a1f0f38fd53f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:17:45.3383992Z","@mt":"Job DEFAULT.9095148d-266a-470d-b526-98b8b9daa606 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2df53c4b-8af0-4056-8ee8-25cafd780daa\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:17:45.3384003Z","@mt":"Job DEFAULT.01c21490-915c-4ba5-a2f9-084fa72b55c1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'User.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:340d5f11-6f16-4dbd-8dce-a1f0f38fd53f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:17:45.5355038Z","@mt":"Job DEFAULT.2fc32914-deb8-4fd9-b1a8-faf394421eb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8ace5f4e-750f-42fb-9c4c-c53550dc261d\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:00.1648568Z","@mt":"Job DEFAULT.2fc32914-deb8-4fd9-b1a8-faf394421eb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2df53c4b-8af0-4056-8ee8-25cafd780daa\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:00.3469794Z","@mt":"Job DEFAULT.01c21490-915c-4ba5-a2f9-084fa72b55c1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'User.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8ace5f4e-750f-42fb-9c4c-c53550dc261d\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:00.3472467Z","@mt":"Job DEFAULT.9095148d-266a-470d-b526-98b8b9daa606 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:340d5f11-6f16-4dbd-8dce-a1f0f38fd53f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:15.4158056Z","@mt":"Job DEFAULT.01c21490-915c-4ba5-a2f9-084fa72b55c1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'User.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:340d5f11-6f16-4dbd-8dce-a1f0f38fd53f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:15.4661615Z","@mt":"Job DEFAULT.2fc32914-deb8-4fd9-b1a8-faf394421eb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2df53c4b-8af0-4056-8ee8-25cafd780daa\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:18:15.4661747Z","@mt":"Job DEFAULT.9095148d-266a-470d-b526-98b8b9daa606 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'user.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8ace5f4e-750f-42fb-9c4c-c53550dc261d\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:41:29.7400229Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:41:30.7316734Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:41:30.7835817Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T15:41:41.6084150Z","@mt":"Job DEFAULT.f4264d99-d006-4c3e-a69d-88a4ddb50d4d threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 29\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:41.6084216Z","@mt":"Job DEFAULT.c0c79702-5f7b-468c-99a6-ccfe6466ced5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 26\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:41.6084204Z","@mt":"Job DEFAULT.50ab74d5-1601-4813-bc4e-ac99f2d1dc76 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 26\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:45.1554119Z","@mt":"Job DEFAULT.f4264d99-d006-4c3e-a69d-88a4ddb50d4d threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 29\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:45.1674675Z","@mt":"Job DEFAULT.c0c79702-5f7b-468c-99a6-ccfe6466ced5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 26\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:45.1554119Z","@mt":"Job DEFAULT.50ab74d5-1601-4813-bc4e-ac99f2d1dc76 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"FootballBanter\" requested by the login. The login failed.\r\nLogin failed for user 'admin'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 26\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:39490ef2-0e1e-47c0-a2ca-86d486e86238\r\nError Number:4060,State:1,Class:11","Module":"Phrases"}
{"@t":"2020-06-28T15:41:51.1871480Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:41:52.2190725Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:41:52.2883411Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T15:42:00.6400081Z","@mt":"Job DEFAULT.b58480b2-f8a2-4a23-8d5e-0ff3b577e4e5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:90defafd-3509-4154-b8bd-db0daeafc670\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:00.7512546Z","@mt":"Job DEFAULT.27b491ce-aa09-4d95-a7c8-c5f68f0db86a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:58bd580a-0c32-4ddf-a3e2-bde065d3cef3\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:01.0491955Z","@mt":"Job DEFAULT.aef36ccf-61e6-4b32-88bf-e66feb6eb318 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:240499ce-c747-4e8b-b853-8be0804d4695\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:15.3603996Z","@mt":"Job DEFAULT.b58480b2-f8a2-4a23-8d5e-0ff3b577e4e5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:58bd580a-0c32-4ddf-a3e2-bde065d3cef3\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:15.4333017Z","@mt":"Job DEFAULT.aef36ccf-61e6-4b32-88bf-e66feb6eb318 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:240499ce-c747-4e8b-b853-8be0804d4695\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:15.4335029Z","@mt":"Job DEFAULT.27b491ce-aa09-4d95-a7c8-c5f68f0db86a threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:90defafd-3509-4154-b8bd-db0daeafc670\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:42:42.9216594Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:44:20.8309061Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:45:07.2513959Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:45:46.9285774Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:52:14.3080181Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:52:33.0710636Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:52:34.3408914Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:52:34.4000008Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T15:52:55.9041295Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:53:00.1550104Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:53:15.2450492Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:53:30.1586872Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8b5b6910-f696-4a61-a01f-8f9638762b01\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:53:45.2754095Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c8312a1d-8259-4629-9c9c-cb5e12f8a238\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:54:00.1679361Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:54:15.1325162Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c8312a1d-8259-4629-9c9c-cb5e12f8a238\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:54:30.1453886Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8b5b6910-f696-4a61-a01f-8f9638762b01\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:54:45.2352327Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:55:00.2141592Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8b5b6910-f696-4a61-a01f-8f9638762b01\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:55:15.1441556Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c8312a1d-8259-4629-9c9c-cb5e12f8a238\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:55:30.3922043Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c8312a1d-8259-4629-9c9c-cb5e12f8a238\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:55:45.2935705Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8b5b6910-f696-4a61-a01f-8f9638762b01\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:56:00.3753139Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:c8312a1d-8259-4629-9c9c-cb5e12f8a238\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:56:37.4069957Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:56:49.8015260Z","@mt":"Job DEFAULT.d81a7fe7-b8ad-4153-9d31-1db6d8bb6475 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Data'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:01f20b2b-8834-47e6-b141-7406f1f7d09d\r\nError Number:207,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T15:58:41.3029998Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:58:51.9130901Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:59:21.2095050Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:59:48.6503244Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T15:59:49.7698340Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T15:59:49.8292720Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T16:00:10.9829280Z","@mt":"Job DEFAULT.5beb276a-c113-4263-a158-3c938df0703d threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Phrases.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Phrases.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Phrases\\Phrases.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:58ee9a7c-6218-490e-873f-46bd6e76357c\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T16:53:17.0153228Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:12:51.1131252Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:12:52.4896841Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:12:52.5771279Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:26:50.7124479Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:26:53.5316292Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:26:53.6972665Z","@mt":"Quartz started.","Module":"Phrases"}
